---
title: "280 Project"
author: "Almirante, Casuyon, Esteves"
date: "27 Nov 2019"
output: html_document
---


```{r lib, warning = FALSE}
library(tidyverse)
library(knitr)
library(BART)
```

```{r data, warnings = FALSE}
X2015 <- read_csv("datasets/world-happiness/2015.csv")
X2016 <- read_csv("datasets/world-happiness/2016.csv")
X2017 <- read_csv("datasets/world-happiness/2017.csv")

bind_cols(
  x5 = c(names(X2015),""),
  x6 = names(X2016),
  x7 = c(names(X2017),"")
  ) %>% write.csv("test.csv")

X2015 <- X2015 %>% 
  select(-`Standard Error`) %>%
  data.frame() %>% 
  magrittr::set_colnames(c("Country",
      "Region",
      "Happiness Rank",
      "Happiness Score",
      "Economy (GDP per Capita)",
      "Family",
      "Health (Life Expectancy)",
      "Freedom",
      "Trust (Government Corruption)",
      "Generosity",
      "Dystopia Residual")) %>% 
  mutate(year = 2015)

X2016 <- X2016 %>% 
  select(-`Lower Confidence Interval`,
         -`Upper Confidence Interval`) %>% 
  data.frame() %>% 
  magrittr::set_colnames(c("Country",
      "Region",
      "Happiness Rank",
      "Happiness Score",
      "Economy (GDP per Capita)",
      "Family",
      "Health (Life Expectancy)",
      "Freedom",
      "Trust (Government Corruption)",
      "Generosity",
      "Dystopia Residual")) %>% 
  mutate(year = 2016)

X2017 <- X2017 %>% 
  select(-`Whisker.high`,
         -`Whisker.low`) %>%
  data.frame() %>%  
  left_join(X2015[,1:2], by = "Country") %>%
  select(Country,
      Region,
      everything()) %>% 
  magrittr::set_colnames(c("Country",
      "Region",
      "Happiness Rank",
      "Happiness Score",
      "Economy (GDP per Capita)",
      "Family",
      "Health (Life Expectancy)",
      "Freedom",
      "Trust (Government Corruption)",
      "Generosity",
      "Dystopia Residual")) %>% 
  mutate(year = 2017)

nyears <- data_frame(Country = c(X2015$Country,X2016$Country,X2017$Country)) %>% 
  group_by(Country) %>% 
  summarise(nyears = n()) %>%
  arrange(Country)

happiness <- bind_rows(X2015,
                       X2016,
                       X2017) %>% 
  left_join(nyears)

happiness %>% write.csv("datasets/world-happiness/happiness.csv")

```

```{r eda}

DataExplorer::create_report(happiness)

```


